# Generated by Django 5.1.2 on 2024-10-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisdemande',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='fireplace_type',
            field=models.CharField(default='Cheminée à foyer ouvert', max_length=255),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='devis_pictures/'),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
