# Generated by Django 5.1.2 on 2024-10-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_devisdemande_color_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devisdemande',
            name='fireplace_type',
            field=models.CharField(max_length=255),
        ),
    ]
