# Generated by Django 5.1.2 on 2024-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='customer_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='request_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='customer_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devisdemande',
            name='request_completed',
            field=models.BooleanField(default=False),
        ),
    ]
