# Generated by Django 5.1.2 on 2024-11-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_contactmessage_customer_contacted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='produits/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='products.productcategory')),
            ],
        ),
    ]
