# Generated by Django 5.1.2 on 2024-11-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productinfo'),
    ]

    operations = [
    ]
