# Generated by Django 5.1.2 on 2024-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20241112_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('social', 'Social Media')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
