# Generated by Django 5.1.2 on 2024-11-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
